// <auto-generated />
#nullable enable
public static partial class MyMappers
{
    [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
    public static partial global::Bar2 ToBar2(this global::Bar1 bar1)
    {
        var target = new global::Bar2(bar1.X, bar1.Y);
        return target;
    }
}