// <auto-generated />
#nullable enable
namespace ThePackage
{
    public static partial class Mappers
    {
        [global::System.CodeDom.Compiler.GeneratedCode("Riok.Mapperly", "3.6.0.0")]
        public static partial global::ThePackage.Foo1 ToFoo1(this global::ThePackage.Foo2 foo2)
        {
            var target = new global::ThePackage.Foo1(foo2.X, foo2.Y);
            return target;
        }
    }
}